main_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('profile/', views.profile, name='profile'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('login/', auth_views.LoginView.as_view(template_name='recipes/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),# built in django view
    path('recipe/<int:pk>/', views.recipe_detail, name='recipe_detail'),
    path('all_recipes/',views.all_recipes,name='all_recipes'),
    path('delete_recipe/<int:pk>/', views.delete_recipe, name='delete_recipe'),
    path('edit_recipe/<int:pk>/', views.edit_recipe, name='edit_recipe'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Categories(models.Model):
    # id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    # id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=200)
    ingredients=models.TextField(null=True, blank=True)
    steps=models.TextField(null=True, blank=True)
    image=models.ImageField(upload_to='recipes/', null=True, blank=True)
    prep_time=models.IntegerField(help_text="Preparation time in minutes", null=True, blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    category=models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True, blank=True)
    rating = models.IntegerField(null=True,blank=True,default=0,help_text="Rate recipe out of 5")

    def __str__(self):
        return self.title

recipes/forms.py
from django import forms
from .models import Recipe, Categories

class RecipeForm(forms.ModelForm):
    class Meta:
        model =Recipe
        fields = ['title', 'ingredients', 'steps', 'image', 'prep_time', 'category', 'rating']
        widgets = {
    'ingredients': forms.Textarea(attrs={'rows':4, 'placeholder':'List ingredients here'}),
    'steps': forms.Textarea(attrs={'rows':6, 'placeholder':'Describe steps here'}),
    'title': forms.TextInput(attrs={'placeholder':'Recipe Title'}),
    'prep_time': forms.NumberInput(attrs={'placeholder':'Preparation time in minutes'}),
    'rating': forms.NumberInput(attrs={'min':0,'max':5}),
}

recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Recipe
from .forms import RecipeForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def home(request):
    recipes =Recipe.objects.all()
    return render(request,'recipes/home.html',{'recipes':recipes})

def about(request):
    return render(request,'recipes/about.html')

def profile(request):
    recipes = Recipe.objects.filter(user=request.user)
    return render(request,'recipes/profile.html', {'recipes': recipes})

@login_required
def add_recipe(request):
    if request.method=='POST':
        form=RecipeForm(request.POST,request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)  
            recipe.user = request.user       
            recipe.save()                    
            return redirect('home')
    else:
        form=RecipeForm()
    return render(request,'recipes/add_recipe.html',{'form':form})

@login_required
def delete_recipe(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk, user=request.user)  
    if request.method == 'POST':
        recipe.delete()
        return redirect('profile')

@login_required
def edit_recipe(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk, user=request.user)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('profile')  
    else:
        form = RecipeForm(instance=recipe)
    return render(request, 'recipes/edit_recipe.html', {'form': form})


def recipe_detail(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    return render(request, 'recipes/recipe_detail.html', {'recipe': recipe})

def all_recipes(request):
    recipes =Recipe.objects.all()
    return render(request,'recipes/all_recipes.html',{'recipes':recipes})

recipes/templates/Base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>


    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <meta charset="UTF-8">
    <title>My Recipes</title>
    
</head>
<body>        
    
    <nav class="navbar">
         <div class ="site-name">
            <p>My Recipe Site <img src="{% static 'img/websiteIcon.png' %}" alt="Icon" class="site-icon"></p>
        </div>
        <div class="nav-links">
        <a href="{% url 'home' %}">Home </a>
        <a href="{% url 'about' %}">About</a>

        {% if user.is_authenticated %}
         <a href="{% url 'add_recipe' %}">Add Recipe</a>
            <a href="{% url 'profile' %}">Profile</a>
            <form method="post" action="{% url 'logout' %}" style="display:inline;">
                {% csrf_token %}
                <button type="submit" style="background:none; border:none; color:rgb(0, 0, 0); cursor:pointer; ">Logout</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
        </div>
    
        
    </nav>

    <main>
    {% block content %}
    {% endblock content %}
    </main>
     <footer class="footer">
        <p>&copy; 2025 My Recipe Website</p>
    </footer>
</body>

</html>

recipes/templates/recipes/about.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}

<style>
        body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
}
main {
    flex: 1; 
    display: flex;
    justify-content: center;
    align-items: center;
}
    .container_about {
    display: flex;
    align-items: center; 
    justify-content: center;
    gap: 30px;
    flex-wrap: wrap;
    padding: 30px;
}

.left_about{
    flex: 1;
    max-width: 500px;
}
.right_about {
    flex: 1;
    display: flex;
    justify-content: center;
}

.right_about img {
    width: 100%;
    max-width: 500px;
    height: auto;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0,0,0,0.2);}
    .card_about {
    background-color: rgba(255, 255, 255, 0.9);
    padding: 20px;
    border-radius: 15px;
    box-shadow: 0 4px 8px rgba(0,0,0,0.2);
}


</style>

<div class="container_about">
    <div class="left_about">
    <div class="card_about">
<h1>Welcome To Our Recipe Platform</h1>
<p>Welcome to our recipe website! We are passionate about sharing delicious recipes from around the world.</p>
</div>
<br>
<div class="card_about">
<h2>Our Mission</h2>
<p>Our mission is to make cooking accessible and enjoyable for everyone, from beginners to professional chefs. We aim to inspire creativity in the kitchen and connect people through the joy of food.</p>
</div>
<br>
<div class="card_about">

<h2>Contact Us</h2>
<p>
    Email: <a href="mailto:sawsan.s@ieee.org">sawsan.s@ieee.org</a>
</p>
<pr> Phone: +962787182884</pr>
</div>
    </div>
<div class="right_about">
    <img src="{%static 'img/right.jpg' %}" alt="About image">
</div>
</div>
{% endblock content %}

recipes/templates/recipes/add_recipe.html
{% extends 'Base.html' %}
{% load static%}
{% block content %}
<style>
    body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
}
main {
    flex: 1; 
    display: flex;
    justify-content: center;
    align-items: center;
}
    .card_add{
    background-color: rgba(255, 255, 255, 0.9); 
    padding: 30px;
    border-radius: 15px;
    box-shadow: 0 4px 10px rgba(0,0,0,0.3);
    max-width: 400px;
    width: 100%;   
    display: flex;
    flex-direction: column;  
    align-items: center;
    justify-content: center;  
    }

    .card_add h1 {
        text-align: center;
        margin-bottom: 20px;
    }

    .card_add p {
        margin-bottom: 15px;
        align-items: center;
        display: flex;
        justify-content: space-between;
        
    }

    .card_add button {
        display: block;
        width: 100%;
        padding: 10px;
        background-color: #9e5b7a;
        color: white;
        border: none;
        border-radius: 8px;
        cursor: pointer;
        font-size: 16px;
    }

    .card_add  button:hover {
        background-color: #7a4160;
    }
</style>

<div class="card_add">

<h1>Add Your New Recipe</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <p><label for="id_title">Title:</label>
    {{ form.title }}</p>

    <p><label for="id_ingredients">Ingredients:</label>
    {{ form.ingredients }}</p>

    <p><label for="id_steps">Steps:</label>
    {{ form.steps }}</p>

    <p><label for="id_image">Image:</label>
    {{ form.image }}</p>

    <p><label for="id_prep_time">Preparation Time (minutes):</label>
    {{ form.prep_time }}</p>

    <p><label for="id_category">Category:</label>
    {{ form.category }}</p>

    <p><label for="id_rating">Rating (0-5):</label>
    {{ form.rating }}</p>

    <button type="submit">Save Recipe</button>
</form>
</div>
{% endblock content %}

recipes/templates/recipes/all_recipes.html
{% extends 'Base.html' %}
{% load static %}

{% block content %}
<h1> All Recipes</h1>
{% for recipe in recipes %}
    <div class="recipe-card">
        <h2><a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.title }}</a></h2>
        <p>{{ recipe.description|truncatewords:20 }}</p>
        {% if recipe.image %}
            <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}">
        {% endif %}
    </div>
{% empty %}
    <p>No recipes available.</p>
{% endfor %}
{% endblock content%}

recipes/templates/recipes/edit_recipe.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}

<style>
body {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
}
main {
    flex: 1; 
    display: flex;
    justify-content: center;
    align-items: center;
}
.card_add{
    background-color: rgba(255, 255, 255, 0.9); 
    padding: 30px;
    border-radius: 15px;
    box-shadow: 0 4px 10px rgba(0,0,0,0.3);
    max-width: 800px;
    width: 100%;   
    display: flex;
    flex-direction: column;  
    align-items: center;
    justify-content: center;  
}

.card_add h1 {
    text-align: center;
    margin-bottom: 20px;
}

.card_add p {
    margin-bottom: 24px;
    display: flex;
    justify-content: space-between;
    width: 100%;
}

.card_add input, .card_add select, .card_add textarea {
    width: 80%; 
    padding: 2px;
    border-radius: 5px;
    border: 1px solid #ccc;
}

.card_add button {
    display: block;
    width: 100%;
    padding: 10px;
    background-color: #9e5b7a;
    color: white;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    font-size: 16px;
    margin-top: 10px;
}

.card_add button:hover {
    background-color: #7a4160;
}

</style>

<div class="card_add">
    <h1>Edit Recipe</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <p><label for="id_title">Title:</label>
        {{ form.title }}</p>

        <p><label for="id_ingredients">Ingredients:</label>
        {{ form.ingredients }}</p>

        <p><label for="id_steps">Steps:</label>
        {{ form.steps }}</p>

        <p><label for="id_image">Image:</label>
        {{ form.image }}</p>

        <p><label for="id_prep_time">Preparation Time (minutes):</label>
        {{ form.prep_time }}</p>

        <p><label for="id_category">Category:</label>
        {{ form.category }}</p>

        <p><label for="id_rating">Rating (0-5):</label>
        {{ form.rating }}</p>

        <button type="submit">Save Changes</button>
    </form>
</div>

{% endblock content %}

recipes/templates/recipes/home.html
{% extends 'Base.html' %}
{% load static %}

{% block content %}
<style>
    .recipes-grid {
    display: grid;
    grid-template-columns: repeat(3 , 1fr); 
    gap: 50px;
    padding: 30px;
    justify-items: center; }

    .card{
        background-color: white;
        padding: 15px;
        margin: 10px;
        height: 600px;

        overflow: hidden;
        text-align: center;
        box-shadow: 0 4px 6px  rgba(0,0,0,0.1) ;
        width: 100%; 
    }
    .card img {
        object-fit: cover;
        display: block;
        margin-bottom: 10px;
        width: 100%;
        height:500px;
    }
@media (max-width: 1024px) {
    .recipes-grid {
        grid-template-columns: repeat(2, 1fr);
    }
}

@media (max-width: 600px) {
    .recipes-grid {
        grid-template-columns: 1fr;
    }
}
    
</style>
<h1 style="text-align: center;">Welcome to Recipe Home Page 🍳</h1>


<h3 style="text-align: center;"> You can find All Recipes here </h3>
<div class="recipes-grid">
{% for recipe in recipes %}
<div class ="card">
    
        {% if recipe.image %}
            <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}">
            {% endif %}
           <h2><a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.title }}</a></h2>
        
    </div>
{% empty %}
    <p>No recipes available.</p>
{% endfor %}
</div>

{% endblock content %}

recipes/templates/recipes/login.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
<style>
    body {
     background-image: url('../img/add_recipe_cover.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
        background-attachment: fixed;
        display: flex;
        flex-direction: column;
        min-height: 100vh;}
main {
    flex: 1; 
    display: flex;
    justify-content: center;
    align-items: center;
}
h2 {
    margin-left: 40px;   
    margin-right: 20px; 
}
</style>
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock content %}

recipes/templates/recipes/profile.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}

<style>
    .recipes-grid {
    display: grid;
    grid-template-columns: repeat(3 , 1fr); 
    gap: 50px;
    padding: 30px;
    justify-items: center; }

    .card{
        background-color: white;
        padding: 15px;
        margin: 10px;
        height: 550px;
        overflow: hidden;
        text-align: center;
        transition: transform 0.2s ease;
        box-shadow: 0 4px 6px  rgba(0,0,0,0.1) ;
        width: 100%; 
    }
    .card img {
        object-fit: cover;
        display: block;
        margin-bottom: 10px;
        width: 100%;
        height:400px;
    }
    .remove-btn {
    color: red;
    background: none;
    border: none;
    cursor: pointer;
    font-weight: bold;
    margin-top: 10px;
}
@media (max-width: 1024px) {
    .recipes-grid {
        grid-template-columns: repeat(2, 1fr);
    }
}

@media (max-width: 600px) {
    .recipes-grid {
        grid-template-columns: 1fr;
    }
}
    
</style>
<h2 style="text-align: center;"> Here You can Find all your recipes 👩‍🍳👨‍🍳</h2>
<div class="recipes-grid">
    {% for recipe in recipes %}
    <div class="card">
        {% if recipe.image %}
            <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}">
        {% endif %}
        <h2><a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.title }}</a></h2>
         <a href="{% url 'edit_recipe' recipe.pk %}" class="edit-btn">Edit</a>
        
         <form method="post" action="{% url 'delete_recipe' recipe.pk %}">
            {% csrf_token %}
            <button type="submit" class="remove-btn">Remove</button>
        </form>
    </div>
    {% empty %}
        <p>No recipes found.</p>
    {% endfor %}
</div>

{% endblock content %}

recipes/templates/recipes/recipe_detail.html
{% extends 'Base.html' %}
{% block content%}
<style>
    .card_details {
    background-color: rgba(255, 255, 255, 0.9);
    padding: 20px;
    border-radius: 15px;
    box-shadow: 0 4px 8px rgba(0,0,0,0.2);
    margin: 10px;
}
</style>
{% load static %}
<h1  style="text-align: center;">{{ recipe.title }}</h1>
<div class="container">
    <div class="left card">
        {% if recipe.image %}
        <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}">
        <p><strong>Rating</strong>: {{ recipe.rating }} / 5</p>
        <p> <strong>Preparation Time</strong> :{{ recipe.prep_time }} minutes</p>
        <p><strong>Category</strong>: {{ recipe.category.name }}</p>
        {% else %}
        <p>No image available.</p>
    {% endif %}
</div>

    <div class="right">
        
        <div class="card_details">
        <h2> Ingredients</h2>
        <p>{{ recipe.ingredients|linebreaksbr }}</p></div>
        <div class="card_details">
        <h2 > Steps</h2>
        <p>{{ recipe.steps|linebreaksbr }}</p>
</div>
    </div>
    
</div>

{% endblock content%}